# This is a basic workflow to help you get started with Actions

name: Blank

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout this repo with token, along with its private submodules
    - uses: actions/checkout@v2
      with:
        submodules: true
        fetch-depth: 0
        token: ${{ secrets.PAT }}

    - name: Check what was checked out
      run: |
        ls -lah .
        ls -lah ./this-is-private
        cat ./this-is-private/README.md
